before_script:
  - apt-get update -qq && apt-get install -y -qq libhdf5-dev
  - pip install -U pip setuptools wheel
  - make install

test:
    image: python:3.7.0
    script:
        - make test
    junit: reports/junit.xml

doc:
    image: python:3.7.0
    script:
        - cd doc && make doc
