image: docker.km3net.de/base/python:3

stages:
  - test
  - coverage
  - doc

before_script:
  - make install

test-py2:
    image: docker.km3net.de/base/python:2
    stage: test
    script:
        - make test
        - make test-km3modules
    artifacts:
      reports:
        junit: "reports/junit*.xml"

test-py3:
    image: docker.km3net.de/base/python:3
    stage: test
    script:
        - make test
        - make test-km3modules
    artifacts:
      reports:
        junit: "reports/junit*.xml"

coverage:
    stage: coverage
    script:
        - make test-cov
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

pages:
    stage: doc
    script:
        - cd doc && make html
        - mv _build/html ../public/
    artifacts:
        paths:
            - public
