image: docker.km3net.de/base/python:3

stages:
  - test
  - coverage
  - doc
  - docker

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: docker.km3net.de/test/km3pipe:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: docker.km3net.de/test/km3pipe:$CI_COMMIT_TAG

before_script:
  - make install

test-py2:
    image: docker.km3net.de/base/python:2
    stage: test
    script:
        - make test
        - make test-km3modules
    artifacts:
      reports:
        junit: "reports/junit*.xml"

test-py3.5:
    image: docker.km3net.de/base/python:3.5
    stage: test
    script:
        - make test
        - make test-km3modules
    artifacts:
      reports:
        junit: "reports/junit*.xml"

test-py3.6:
    image: docker.km3net.de/base/python:3.6
    stage: test
    script:
        - make test
        - make test-km3modules
    artifacts:
      reports:
        junit: "reports/junit*.xml"

test-py3.7:
    image: docker.km3net.de/base/python:3.7
    stage: test
    script:
        - make test
        - make test-km3modules
    artifacts:
      reports:
        junit: "reports/junit*.xml"

coverage:
    image: docker.km3net.de/base/python:3.6
    stage: coverage
    script:
        - make test-cov
        - ls
        - ls reports/coverage
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    artifacts:
        paths:
            - reports/coverage

pages:
    stage: doc
    script:
        - cd doc && make html
        - mv _build/html ../public/
        - cd .. && mv reports/coverage public/coverage
    artifacts:
        paths:
            - public

docker:
  image: docker:stable
  services:
    - docker:dind
  stage: docker
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  tags:
    - docker
  only:
    - tags

release-image:
  image: docker:stable
  services:
    - docker:dind
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - tags
