image: docker.km3net.de/python:3

before_script:
  - make install

test:
    script:
        - make test
        - make test-km3modules
        - make test-cov
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    artifacts:
      reports:
        junit: "reports/junit*.xml"

pages:
    script:
        - cd doc && make html
        - mv _build/html ../public/
    artifacts:
        paths:
            - public
