image: docker.km3net.de/base/python:3

stages:
  - test
  - coverage
  - doc

before_script:
  - make install

test-py2:
    image: docker.km3net.de/base/python:2
    stage: test
    script:
        - make test
        - make test-km3modules
    artifacts:
      reports:
        junit: "reports/junit*.xml"

test-py3.5:
    image: docker.km3net.de/base/python:3.5
    stage: test
    script:
        - make test
        - make test-km3modules
    artifacts:
      reports:
        junit: "reports/junit*.xml"

test-py3.6:
    image: docker.km3net.de/base/python:3.6
    stage: test
    script:
        - make test
        - make test-km3modules
    artifacts:
      reports:
        junit: "reports/junit*.xml"

test-py3.7:
    image: docker.km3net.de/base/python:3.7
    stage: test
    script:
        - make test
        - make test-km3modules
    artifacts:
      reports:
        junit: "reports/junit*.xml"

coverage:
    image: docker.km3net.de/base/python:3.6
    stage: coverage
    script:
        - make test-cov|grep TOTAL| awk  -F " " '{printf "COVERAGE: %4.4f%%\n", (1-$3/$2)*100 }'
    coverage: '/COVERAGE ([0-9]{1,4}\.[0-9]{1,4}%)/'
    artifacts:
        paths:
            - reports/coverage

pages:
    stage: doc
    script:
        - cd doc && make html
        - mv _build/html ../public/
        - cd .. && mv reports/coverage public/coverage
    artifacts:
        paths:
            - public
