name: km3pipe

dependencies:
  - python=3.5*
  - hdf5=1.8.17=1
  - numpy>=1.12
  - matplotlib
  - scipy>=0.19
  - pillow
  - pandas
  - h5py
  - pip:
    - sphinx-gallery>=0.1.12
    - sphinx-rtd-theme
    - sphinx>=1.6.3
    - sphinxcontrib-napoleon
    - sphinxcontrib-programoutput
    - sphinxcontrib-websupport
    - numpydoc
    - pydocstyle
    - seaborn
    - sklearn
    - statsmodels
    - tables
