name: km3pipe

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.5*
  - hdf5=1.8.17=1
  - pip>=9.0.1
  - setuptools>=24.3
  - numpy>=1.12
  - numexpr
  - pandas
  - matplotlib>=2.2.0
  - scipy>=0.19
  - pillow
  - pytables
  - h5py
  - scikit-learn
  - numexpr
  - patsy
  - statsmodels>=0.9
  - urwid
  - pip:
    - sphinx>=1.6.3
    - sphinx-gallery>=0.1.12
    - sphinx-rtd-theme>=0.3
    - sphinxcontrib-napoleon>=0.6.1
    - sphinxcontrib-programoutput>=0.11
    - sphinxcontrib-websupport>=1.0.1
    - numpydoc>=0.7.0
    - docopt
    - controlhost
