name: km3pipe

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.6.0=0
  - hdf5=1.8.17=1
  - pip=9.0.1=py36_1
  - numpy
  - pandas
  - matplotlib
  - scipy
  - cython
  - pillow
  - pip:
    - sphinx==1.5.3
    - sphinx-gallery==0.1.8
    - sphinxcontrib-napoleon==0.6.1
