language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
#   - "nightly"
#

before_install:
    - uname -a
    - free -m
    - df -h
    - pip install -U virtualenv
    - virtualenv --python=python venv
    - source venv/bin/activate
    - python -V
    - echo $TRAVIS_PYTHON_VERSION
    - pip install -U pip setuptools
    - pip install -U numpy cython
    - pip install -U pytest
    - ls -al
    - pip install .

install: "pip install -r requirements.txt"

script: py.test km3pipe
